name: mobi_shop
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  very_good_analysis: ^7.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  flutter_spinkit: ^5.2.1
  animate_do: ^4.1.1
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  icons_launcher: ^3.0.0
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/svg/


  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
  #

icons_launcher:
  image_path: "assets/icons/icon app.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
# dart run icons_launcher:create